export const collectionToPromptToImage: {
  [key: string]: { [key: string]: number };
} = {
  'the-space-collection': {
    'planet, trending on artstation, stars and moon, 8k, cinematic composition': 0,
    'large space dreamscape with galaxies and swirling colors of space dust, exploding stars, black holes, planets': 1,
    'vertical, limit, galaxy, universe, emotion, uhd hyperrealistic photorealisitc hyperdetailed detailed, in space': 2,
    'decelerating into a star - system buried in a nebula, tendrils, tentacles, mass of limbs, intertwined beings floating in space, high quality award - winning digital art, 4 k': 3,
    'Supernovae event collision galaxies, Greg Rutkowski': 4,
    'a particles simulation of the universe, Blender 3D, Unreal Engine, 8k': 5,
    'horizon of a colorful exoplanet, view from space far away, artstation, cinematic, by greg rutkowski, scifi, digital art': 6,
    'a black hole. gargantua, scifi scene, vacuum of space, volumetric lighting, high resolution, very detailed, concept art': 7,
    'another planet, extraterrestial, astronaut sky with stars and galaxies, milky way nebula, volumetric light, detailed background, unreal engine, trending on artstation, by rossdraws, thomas kinkade': 8,
    'chaotic volumetric space nebula, Helix nebula, Pillars of Creation, epic cosmic starfield scene, made by Hubble': 9,
    'sunset on a distant planet high resolution beautiful lighting soft colors unreal engine 4 k wallpaper': 10,
    'planet in nebula by h. p. lovecraft, abaddon and magali villeneuve, ghibli moebius, 8 k, epic scene, scifi, unreal engine, trending on cg station. masterpiece.': 11,
    'large scaling galaxy, intertwining bright colors, supernova, fire, collapsing into a black hole full of beautiful galaxies, bright hd ultra color, bright stars, space, bright': 12,
    'open your eyes to the cosmic rainbow cosmos, digital art, hyper detailed, vibrant, artstation, deep and dense coloration.': 13,
  },
  'the-dog-collection': {
    'A polite shiba inu eating sushi in a Koma room, very beautiful, watercolor': 0,
    'cavapoo running on the beach, ocean, photorealistic': 1,
    'shiba inu sitting on times square': 2,
    'shiba inu painted, old style': 3,
    'cavapoo playing in the woods': 4,
    'golden retriever chilling on the beach, sunny': 5,
    'a photorealistic photograph of a smiling white Bichon Frisé puppy riding in red wagon and eating french fries during sunset at the beach, well-rendered, Unreal Engine, 4K HD': 6,
    'happy corgi running on times square': 7,
    'Golden labradoodle puppy surfing': 8,
    'corgi running on mars, space, detailed': 9,
    'a cream-colored havanese snorkeling in a tropical reef, gopro photo, 4k': 10,
    'dog wearing sunglasses relaxing in a pool floater, cinestill': 11,
    'Golden labradoodle puppy sky diving and smiling': 12,
    'cute fluffy golden labrador puppy sitting in grass flower spring landscape detailed painting 4 k': 13,
  },
};
